### ISSUE TITLE
class vs. ID

### ISSUE THREAD

**Issue by ad3429** [JerryBaboona/prj-rev-bwfs-dasmoto#1]
https://github.com/JerryBaboona/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/index.html#L11-L27

It seems you assigned classes to your brushes, frames and paint elements but you should have assigned them an ID instead. Classes are better suited for when you want to style groups of elements the same way, while IDs are better for when you want to style unique, individual elements, which is the case here. You can read more about the difference here:

https://css-tricks.com/the-difference-between-id-and-class/

**Comment by JerryBaboona** [comment]
I've now updated appropriately.

When I first wrote the code I had been thinking to use IDs but had in mind the warnings during the course that IDs should be used sparingly.
