### ISSUE TITLE
make sure to comment the main parts of your code

### ISSUE THREAD

**Issue by ad3429** [JerryBaboona/prj-rev-bwfs-dasmoto#2]
https://github.com/JerryBaboona/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/index.html#L1-L37

In future projects, make sure to comment the main parts of your code. This becomes increasingly important as your projects become more complex

**Comment by JerryBaboona** [comment]
Thanks for the feedback, I understanding that commenting will be really important as these projects become more complicated. I have added some comments in index.html to demarcate the main areas of the page.
