### ISSUE TITLE
CSS is clean and succinct

### ISSUE THREAD

**Issue by ad3429** [JerryBaboona/prj-rev-bwfs-dasmoto#3]
https://github.com/JerryBaboona/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/resources/css/style.css#L5-L29

Your CSS is clean, short and succinct. Great job! One are of improvement here is to make sure to comment the main parts of your stylings so that when you come back to your code you know exactly why you decided to style something a particular way.

**Comment by JerryBaboona** [comment]
Thanks for the feedback. I have added comments in the CSS file
