### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by ad3429** [JerryBaboona/prj-rev-bwfs-dasmoto#5]
**Summary Grade: Satisfactory **
 
Good job! Your files are organized nicely, and you did a great job of following the client specification -- this is an important skill to have as a developer and you seem to understand that . Moreover, you generally followed excellent code practice, so make sure to keep that up! 
 
I have made some comments in your code to take note of. First off, make sure to comment the main parts of your code in future projects. Next off, your brushes, frames and paint sections should be id’s instead of classes since they are individual, unique elements. Classes are better suited for when you want to style groups of an element. You can read more about classes vs id’ here:
 
https://css-tricks.com/the-difference-between-id-and-class/
 
Great job overall! As a further challenge, try using css to design your webpage even further! You did a great job in following the client specification, but for your own practice you should see how creative you can get by taking the design/styling of your site to the next level (for example, you can try experimenting with background colors on your other divs)

**Comment by JerryBaboona** [comment]
Thanks again for the feedback, I found it really useful!

I have made the changes you have suggested and pushed them to this repo. Thanks again!
